[2025-10-06T15:55:18.842+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:55:18.843+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:55:18.844+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:55:18.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:55:18.853+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:55:18.851+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:55:18.853+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:55:18.867+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.026 seconds
[2025-10-06T15:55:49.097+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:55:49.097+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:55:49.098+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:55:49.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:55:49.102+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:55:49.101+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:55:49.102+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:55:49.113+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.019 seconds
[2025-10-06T15:56:19.352+0000] {processor.py:153} INFO - Started process (PID=144) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:56:19.352+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:56:19.352+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:56:19.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:56:19.356+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:56:19.355+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:56:19.356+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:56:19.363+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.013 seconds
[2025-10-06T15:56:49.643+0000] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:56:49.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:56:49.645+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:56:49.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:56:49.650+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:56:49.648+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:56:49.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:56:49.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.037 seconds
[2025-10-06T15:57:19.934+0000] {processor.py:153} INFO - Started process (PID=266) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:57:19.935+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:57:19.936+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:57:19.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:57:19.941+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:57:19.939+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:57:19.941+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:57:19.955+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.025 seconds
[2025-10-06T15:57:50.190+0000] {processor.py:153} INFO - Started process (PID=327) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:57:50.191+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:57:50.191+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:57:50.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:57:50.194+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:57:50.193+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:57:50.194+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:57:50.205+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.016 seconds
[2025-10-06T15:58:20.464+0000] {processor.py:153} INFO - Started process (PID=368) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:58:20.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:58:20.466+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:58:20.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:58:20.470+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:58:20.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:58:20.470+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:58:20.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.021 seconds
[2025-10-06T15:58:50.741+0000] {processor.py:153} INFO - Started process (PID=429) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:58:50.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:58:50.742+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:58:50.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:58:50.745+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:58:50.744+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:58:50.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:58:50.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.015 seconds
[2025-10-06T15:59:20.999+0000] {processor.py:153} INFO - Started process (PID=490) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:59:21.000+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:59:21.000+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:59:21.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:59:21.004+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:59:21.003+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:59:21.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:59:21.017+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.021 seconds
[2025-10-06T15:59:51.244+0000] {processor.py:153} INFO - Started process (PID=551) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T15:59:51.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T15:59:51.245+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:59:51.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T15:59:51.250+0000] {logging_mixin.py:137} INFO - [2025-10-06T15:59:51.249+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T15:59:51.250+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T15:59:51.261+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.019 seconds
[2025-10-06T16:00:21.467+0000] {processor.py:153} INFO - Started process (PID=592) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:00:21.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:00:21.468+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:00:21.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:00:21.471+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:00:21.470+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:00:21.471+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:00:21.483+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.019 seconds
[2025-10-06T16:00:51.700+0000] {processor.py:153} INFO - Started process (PID=653) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:00:51.702+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:00:51.702+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:00:51.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:00:51.707+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:00:51.706+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:00:51.708+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:00:51.721+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.024 seconds
[2025-10-06T16:01:21.984+0000] {processor.py:153} INFO - Started process (PID=714) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:01:21.984+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:01:21.985+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:01:21.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:01:21.988+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:01:21.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:01:21.989+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:01:22.005+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.025 seconds
[2025-10-06T16:01:52.269+0000] {processor.py:153} INFO - Started process (PID=775) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:01:52.270+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:01:52.270+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:01:52.270+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:01:52.275+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:01:52.274+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:01:52.275+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:01:52.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.021 seconds
[2025-10-06T16:02:22.540+0000] {processor.py:153} INFO - Started process (PID=816) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:02:22.541+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:02:22.542+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:02:22.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:02:22.545+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:02:22.545+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:02:22.546+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:02:22.558+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.022 seconds
[2025-10-06T16:02:52.844+0000] {processor.py:153} INFO - Started process (PID=877) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:02:52.845+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:02:52.846+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:02:52.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:02:52.857+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:02:52.855+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:02:52.857+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:02:52.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.035 seconds
[2025-10-06T16:03:23.144+0000] {processor.py:153} INFO - Started process (PID=938) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:03:23.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:03:23.145+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:03:23.145+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:03:23.148+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:03:23.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:03:23.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:03:23.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.016 seconds
[2025-10-06T16:03:53.423+0000] {processor.py:153} INFO - Started process (PID=999) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:03:53.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:03:53.424+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:03:53.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:03:53.427+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:03:53.426+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:03:53.427+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:03:53.436+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.015 seconds
[2025-10-06T16:04:23.718+0000] {processor.py:153} INFO - Started process (PID=1040) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:04:23.719+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:04:23.719+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:04:23.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:04:23.724+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:04:23.723+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:04:23.724+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:04:23.738+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.024 seconds
[2025-10-06T16:04:53.987+0000] {processor.py:153} INFO - Started process (PID=1101) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:04:53.988+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:04:53.989+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:04:53.989+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:04:53.993+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:04:53.992+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:04:53.993+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:04:54.005+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.022 seconds
[2025-10-06T16:05:24.291+0000] {processor.py:153} INFO - Started process (PID=1162) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:05:24.294+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:05:24.297+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:05:24.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:05:24.303+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:05:24.302+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:05:24.304+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:05:24.318+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.032 seconds
[2025-10-06T16:05:54.562+0000] {processor.py:153} INFO - Started process (PID=1212) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:05:54.563+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:05:54.563+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:05:54.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:05:54.566+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:05:54.565+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:05:54.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:05:54.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.016 seconds
[2025-10-06T16:06:24.815+0000] {processor.py:153} INFO - Started process (PID=1264) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:06:24.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:06:24.816+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:06:24.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:06:24.819+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:06:24.818+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:06:24.819+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:06:24.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.020 seconds
[2025-10-06T16:06:55.068+0000] {processor.py:153} INFO - Started process (PID=1325) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:06:55.068+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:06:55.069+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:06:55.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:06:55.071+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:06:55.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:06:55.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:06:55.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.018 seconds
[2025-10-06T16:07:25.286+0000] {processor.py:153} INFO - Started process (PID=1386) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:07:25.287+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:07:25.288+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:07:25.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:07:25.291+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:07:25.290+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:07:25.291+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:07:25.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.019 seconds
[2025-10-06T16:07:55.550+0000] {processor.py:153} INFO - Started process (PID=1427) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:07:55.550+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:07:55.551+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:07:55.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:07:55.554+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:07:55.553+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:07:55.554+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:07:55.567+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.019 seconds
[2025-10-06T16:08:25.837+0000] {processor.py:153} INFO - Started process (PID=1488) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:08:25.837+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:08:25.838+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:08:25.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:08:25.843+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:08:25.841+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:08:25.843+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:08:25.857+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.025 seconds
[2025-10-06T16:08:56.143+0000] {processor.py:153} INFO - Started process (PID=1549) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:08:56.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:08:56.144+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:08:56.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:08:56.148+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:08:56.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:08:56.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:08:56.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.021 seconds
[2025-10-06T16:09:26.418+0000] {processor.py:153} INFO - Started process (PID=1610) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:09:26.418+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:09:26.419+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:09:26.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:09:26.421+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:09:26.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:09:26.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:09:26.430+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.014 seconds
[2025-10-06T16:09:56.670+0000] {processor.py:153} INFO - Started process (PID=1657) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:09:56.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:09:56.671+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:09:56.671+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:09:56.674+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:09:56.673+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:09:56.674+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:09:56.685+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.017 seconds
[2025-10-06T16:10:26.917+0000] {processor.py:153} INFO - Started process (PID=1718) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:10:26.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:10:26.918+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:10:26.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:10:26.921+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:10:26.920+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:10:26.922+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:10:26.935+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.022 seconds
[2025-10-06T16:10:57.102+0000] {processor.py:153} INFO - Started process (PID=1778) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:10:57.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:10:57.104+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:10:57.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:10:57.108+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:10:57.107+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:10:57.108+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:10:57.121+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.022 seconds
[2025-10-06T16:11:27.343+0000] {processor.py:153} INFO - Started process (PID=1838) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:11:27.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:11:27.344+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:11:27.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:11:27.347+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:11:27.346+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:11:27.347+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:11:27.358+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.017 seconds
[2025-10-06T16:11:57.544+0000] {processor.py:153} INFO - Started process (PID=1892) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:11:57.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:11:57.544+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:11:57.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:11:57.547+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:11:57.547+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:11:57.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:11:57.557+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.016 seconds
[2025-10-06T16:12:27.750+0000] {processor.py:153} INFO - Started process (PID=1954) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:12:27.750+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:12:27.750+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:12:27.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:12:27.752+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:12:27.752+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:12:27.752+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:12:27.761+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.013 seconds
[2025-10-06T16:12:58.014+0000] {processor.py:153} INFO - Started process (PID=2022) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:12:58.015+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:12:58.016+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:12:58.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:12:58.021+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:12:58.020+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:12:58.021+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:12:58.034+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.025 seconds
[2025-10-06T16:13:28.251+0000] {processor.py:153} INFO - Started process (PID=2075) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:13:28.252+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:13:28.252+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:13:28.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:13:28.254+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:13:28.254+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:13:28.255+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:13:28.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.014 seconds
[2025-10-06T16:13:58.489+0000] {processor.py:153} INFO - Started process (PID=2136) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:13:58.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:13:58.491+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:13:58.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:13:58.496+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:13:58.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:13:58.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:13:58.514+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.029 seconds
[2025-10-06T16:14:28.722+0000] {processor.py:153} INFO - Started process (PID=2197) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:14:28.723+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:14:28.723+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:14:28.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:14:28.726+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:14:28.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:14:28.726+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:14:28.737+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.017 seconds
[2025-10-06T16:14:58.966+0000] {processor.py:153} INFO - Started process (PID=2258) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:14:58.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:14:58.967+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:14:58.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:14:58.971+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:14:58.970+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:14:58.972+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:14:58.986+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.023 seconds
[2025-10-06T16:15:29.272+0000] {processor.py:153} INFO - Started process (PID=2299) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:15:29.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:15:29.275+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:15:29.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:15:29.279+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:15:29.278+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:15:29.279+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:15:29.295+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.026 seconds
[2025-10-06T16:15:59.548+0000] {processor.py:153} INFO - Started process (PID=2360) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:15:59.549+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:15:59.550+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:15:59.550+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:15:59.557+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:15:59.555+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:15:59.557+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:15:59.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.030 seconds
[2025-10-06T16:16:29.834+0000] {processor.py:153} INFO - Started process (PID=2421) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:16:29.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:16:29.835+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:16:29.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:16:29.840+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:16:29.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:16:29.840+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:16:29.854+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.024 seconds
[2025-10-06T16:17:00.146+0000] {processor.py:153} INFO - Started process (PID=2482) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:17:00.154+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:17:00.155+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:17:00.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:17:00.163+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:17:00.162+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:17:00.165+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:17:00.186+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.042 seconds
[2025-10-06T16:17:30.436+0000] {processor.py:153} INFO - Started process (PID=2523) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:17:30.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:17:30.437+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:17:30.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:17:30.442+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:17:30.441+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:17:30.443+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:17:30.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.027 seconds
[2025-10-06T16:18:00.700+0000] {processor.py:153} INFO - Started process (PID=2584) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:18:00.702+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:18:00.702+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:18:00.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:18:00.706+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:18:00.705+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:18:00.707+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:18:00.721+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.024 seconds
[2025-10-06T16:18:30.934+0000] {processor.py:153} INFO - Started process (PID=2645) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:18:30.935+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:18:30.936+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:18:30.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:18:30.941+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:18:30.940+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:18:30.941+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:18:30.956+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.026 seconds
[2025-10-06T16:19:01.187+0000] {processor.py:153} INFO - Started process (PID=2686) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:19:01.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:19:01.188+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:19:01.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:19:01.191+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:19:01.190+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:19:01.191+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:19:01.201+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.018 seconds
[2025-10-06T16:19:31.443+0000] {processor.py:153} INFO - Started process (PID=2747) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:19:31.444+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:19:31.445+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:19:31.445+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:19:31.448+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:19:31.448+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:19:31.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:19:31.465+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.025 seconds
[2025-10-06T16:20:01.711+0000] {processor.py:153} INFO - Started process (PID=2808) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:20:01.712+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:20:01.712+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:20:01.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:20:01.717+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:20:01.716+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:20:01.717+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:20:01.730+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.023 seconds
[2025-10-06T16:20:32.016+0000] {processor.py:153} INFO - Started process (PID=2873) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:20:32.016+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:20:32.017+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:20:32.017+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:20:32.020+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:20:32.019+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:20:32.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:20:32.033+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.022 seconds
[2025-10-06T16:21:02.114+0000] {processor.py:153} INFO - Started process (PID=2918) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:21:02.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:21:02.115+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:21:02.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:21:02.120+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:21:02.119+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:21:02.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:21:02.135+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.026 seconds
[2025-10-06T16:21:32.230+0000] {processor.py:153} INFO - Started process (PID=2983) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:21:32.231+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:21:32.232+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:21:32.232+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:21:32.235+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:21:32.234+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:21:32.235+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:21:32.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.018 seconds
[2025-10-06T16:22:02.472+0000] {processor.py:153} INFO - Started process (PID=3048) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:22:02.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:22:02.473+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:22:02.473+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:22:02.479+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:22:02.477+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:22:02.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:22:02.494+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.028 seconds
[2025-10-06T16:22:32.511+0000] {processor.py:153} INFO - Started process (PID=3093) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:22:32.511+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:22:32.511+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:22:32.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:22:32.514+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:22:32.513+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:22:32.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:22:32.527+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.018 seconds
[2025-10-06T16:23:02.577+0000] {processor.py:153} INFO - Started process (PID=3158) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:23:02.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:23:02.579+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:23:02.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:23:02.582+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:23:02.581+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:23:02.582+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:23:02.597+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.023 seconds
[2025-10-06T16:23:32.622+0000] {processor.py:153} INFO - Started process (PID=3222) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:23:32.623+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:23:32.623+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:23:32.623+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:23:32.627+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:23:32.626+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:23:32.627+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:23:32.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.024 seconds
[2025-10-06T16:24:02.863+0000] {processor.py:153} INFO - Started process (PID=3287) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:24:02.864+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:24:02.865+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:24:02.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:24:02.870+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:24:02.869+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:24:02.870+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:24:02.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.028 seconds
[2025-10-06T16:24:33.144+0000] {processor.py:153} INFO - Started process (PID=3332) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:24:33.145+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:24:33.146+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:24:33.146+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:24:33.149+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:24:33.148+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:24:33.150+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:24:33.166+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.027 seconds
[2025-10-06T16:25:03.400+0000] {processor.py:153} INFO - Started process (PID=3397) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:25:03.401+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:25:03.402+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:25:03.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:25:03.405+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:25:03.404+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:25:03.406+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:25:03.420+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.024 seconds
[2025-10-06T16:25:33.660+0000] {processor.py:153} INFO - Started process (PID=3459) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:25:33.661+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:25:33.661+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:25:33.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:25:33.664+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:25:33.663+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:25:33.664+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:25:33.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.016 seconds
[2025-10-06T16:26:03.874+0000] {processor.py:153} INFO - Started process (PID=3523) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:26:03.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:26:03.875+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:26:03.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:26:03.877+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:26:03.876+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:26:03.877+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:26:03.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.013 seconds
[2025-10-06T16:26:34.143+0000] {processor.py:153} INFO - Started process (PID=3568) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:26:34.143+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:26:34.144+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:26:34.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:26:34.148+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:26:34.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:26:34.149+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:26:34.163+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.024 seconds
[2025-10-06T16:27:04.228+0000] {processor.py:153} INFO - Started process (PID=3633) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:27:04.229+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:27:04.230+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:27:04.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:27:04.235+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:27:04.234+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:27:04.235+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:27:04.251+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.027 seconds
[2025-10-06T16:27:34.303+0000] {processor.py:153} INFO - Started process (PID=3698) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:27:34.304+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:27:34.305+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:27:34.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:27:34.309+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:27:34.308+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:27:34.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:27:34.322+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.023 seconds
[2025-10-06T16:28:04.552+0000] {processor.py:153} INFO - Started process (PID=3743) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:28:04.553+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:28:04.554+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:28:04.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:28:04.559+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:28:04.558+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:28:04.560+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:28:04.577+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.030 seconds
[2025-10-06T16:28:34.634+0000] {processor.py:153} INFO - Started process (PID=3808) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:28:34.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:28:34.635+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:28:34.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:28:34.640+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:28:34.639+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:28:34.640+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:28:34.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.026 seconds
[2025-10-06T16:29:04.732+0000] {processor.py:153} INFO - Started process (PID=3877) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:04.733+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:29:04.734+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:29:04.733+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:04.738+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:29:04.737+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:29:04.738+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:04.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.028 seconds
[2025-10-06T16:29:10.208+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:10.208+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:29:10.208+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:29:10.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:10.213+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:29:10.212+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:29:10.213+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:10.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.015 seconds
[2025-10-06T16:29:40.450+0000] {processor.py:153} INFO - Started process (PID=106) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:40.451+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:29:40.451+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:29:40.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:40.453+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:29:40.453+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:29:40.453+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:29:40.463+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.014 seconds
[2025-10-06T16:30:10.664+0000] {processor.py:153} INFO - Started process (PID=151) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:30:10.665+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:30:10.665+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:30:10.665+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:30:10.668+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:30:10.667+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:30:10.668+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:30:10.681+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.020 seconds
[2025-10-06T16:30:40.929+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:30:40.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:30:40.930+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:30:40.930+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:30:40.932+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:30:40.932+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:30:40.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:30:40.944+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.017 seconds
[2025-10-06T16:31:11.193+0000] {processor.py:153} INFO - Started process (PID=281) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:31:11.193+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:31:11.194+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:31:11.194+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:31:11.195+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:31:11.195+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:31:11.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:31:11.204+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.012 seconds
[2025-10-06T16:31:41.435+0000] {processor.py:153} INFO - Started process (PID=346) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:31:41.435+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:31:41.436+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:31:41.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:31:41.438+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:31:41.437+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:31:41.438+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:31:41.446+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.013 seconds
[2025-10-06T16:32:11.693+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:32:11.694+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:32:11.695+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:32:11.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:32:11.699+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:32:11.698+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:32:11.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:32:11.714+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.025 seconds
[2025-10-06T16:32:41.927+0000] {processor.py:153} INFO - Started process (PID=456) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:32:41.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:32:41.928+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:32:41.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:32:41.933+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:32:41.931+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:32:41.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:32:41.949+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.025 seconds
[2025-10-06T16:33:12.235+0000] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:33:12.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:33:12.237+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:33:12.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:33:12.241+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:33:12.240+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:33:12.241+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:33:12.257+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.028 seconds
[2025-10-06T16:33:34.609+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:33:34.612+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:33:34.614+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:33:34.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:33:34.622+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:33:34.617+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:33:34.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:33:34.638+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.034 seconds
[2025-10-06T16:34:04.674+0000] {processor.py:153} INFO - Started process (PID=106) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:34:04.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:34:04.675+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:34:04.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:34:04.677+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:34:04.676+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:34:04.677+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:34:04.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.013 seconds
[2025-10-06T16:34:34.916+0000] {processor.py:153} INFO - Started process (PID=151) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:34:34.916+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:34:34.917+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:34:34.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:34:34.919+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:34:34.919+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:34:34.920+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:34:34.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.019 seconds
[2025-10-06T16:35:04.961+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:35:04.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:35:04.963+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:35:04.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:35:04.968+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:35:04.966+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:35:04.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:35:04.984+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.028 seconds
[2025-10-06T16:35:35.221+0000] {processor.py:153} INFO - Started process (PID=281) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:35:35.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:35:35.222+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:35:35.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:35:35.225+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:35:35.224+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:35:35.225+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:35:35.235+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.017 seconds
[2025-10-06T16:36:05.457+0000] {processor.py:153} INFO - Started process (PID=333) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:05.458+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:36:05.458+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:36:05.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:05.461+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:36:05.460+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:36:05.461+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:05.473+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.018 seconds
[2025-10-06T16:36:25.871+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:25.871+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:36:25.872+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:36:25.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:25.880+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:36:25.877+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:36:25.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:25.890+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.021 seconds
[2025-10-06T16:36:56.047+0000] {processor.py:153} INFO - Started process (PID=106) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:56.047+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:36:56.048+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:36:56.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:56.050+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:36:56.049+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:36:56.050+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:36:56.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.014 seconds
[2025-10-06T16:37:26.254+0000] {processor.py:153} INFO - Started process (PID=151) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:37:26.254+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:37:26.254+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:37:26.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:37:26.257+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:37:26.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:37:26.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:37:26.267+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.016 seconds
[2025-10-06T16:37:56.423+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:37:56.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:37:56.425+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:37:56.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:37:56.431+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:37:56.429+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:37:56.431+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:37:56.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.032 seconds
[2025-10-06T16:38:26.781+0000] {processor.py:153} INFO - Started process (PID=281) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:38:26.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:38:26.783+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:38:26.783+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:38:26.787+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:38:26.786+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:38:26.787+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:38:26.803+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.026 seconds
[2025-10-06T16:38:56.982+0000] {processor.py:153} INFO - Started process (PID=335) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:38:56.982+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:38:56.983+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:38:56.983+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:38:56.984+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:38:56.984+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:38:56.985+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:38:56.994+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.014 seconds
[2025-10-06T16:39:27.555+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:39:27.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:39:27.556+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:39:27.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:39:27.559+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:39:27.559+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:39:27.560+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:39:27.571+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.019 seconds
[2025-10-06T16:39:57.790+0000] {processor.py:153} INFO - Started process (PID=456) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:39:57.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:39:57.791+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:39:57.791+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:39:57.794+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:39:57.794+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:39:57.795+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:39:57.807+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.020 seconds
[2025-10-06T16:40:27.972+0000] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:40:27.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:40:27.973+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:40:27.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:40:27.977+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:40:27.976+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:40:27.977+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:40:27.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.021 seconds
[2025-10-06T16:40:58.189+0000] {processor.py:153} INFO - Started process (PID=572) to work on /opt/airflow/dags/sandbox.py
[2025-10-06T16:40:58.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sandbox.py for tasks to queue
[2025-10-06T16:40:58.191+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:40:58.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sandbox.py
[2025-10-06T16:40:58.196+0000] {logging_mixin.py:137} INFO - [2025-10-06T16:40:58.195+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sandbox.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sandbox.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T16:40:58.196+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sandbox.py
[2025-10-06T16:40:58.215+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sandbox.py took 0.031 seconds
